apiVersion: 1

datasources:
  - name: Etsy OI Postgres
    uid: etsy_oi_postgres
    type: postgres
    access: proxy
    url: localhost:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: etsy_oi
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true

  - name: Etsy OI ClickHouse
    uid: etsy_oi_clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://localhost:8123
    jsonData:
      defaultDatabase: default
      port: 8123
      protocol: http
      server: localhost
      username: default
    editable: true

